// ReSharper disable InconsistentNaming
namespace LCalc.Tests.TestCases;

public static partial class TestCases
{
    public static readonly string[] Error_ShouldBe_Expected =
    {
        // Function
        "1,2",
        "1+(2,3)",
        "null()",
        "sum()",
        "avg()",
        "abs()",
        "cbrt()",
        "sqrt()",
        "ceiling()",
        "round()",
        "round(1.234, 6)",
        "floor()",
        "gcd()",
        "gcd(1.1 2.2)",
        "gcd(1 2.2)",
        "lcm()",
        "lcm(1.1 2.2)",
        "lcm(1 2.2)",
        "random(1 2 3)",
        "random(1 a)",
        "cos()",
        "sin()",
        "tan()",
        "cot()",
        "log()",
        "|-1)",
        "sin(,,,)",
        // Misc
        "",
        "()",
        "1)",
        "1-",
        "null!",
        "-2!",
        "2.5<<2.5",
        "50!<<50!",
        "2.5||2.5",
        "100!||100!",
        "-n",
        "1~",
        "1&",
        "1+",
        "+1",
        "1 1",
        "2^3^ ^",
        "1-&a=100",
        "&a=",
        "&a='",
        "&foo=",
        "&foo='",
        "&a=1&a=1",
        "1 &fmt=error",
        // Computed variable
        "a&a=()",
        "a&a=([",
        "a&a=(&b=1",
        // Special number
        "0x",
        "0b",
        "0o",
        "0xfg",
        "0b12",
        "0o89",
        // Custom function
        "[t()=t()]t()",
        "[a()=)]",
        "[a(x x)=1]",
        "[a(])",
        "[a(1)]",
        "[a()=1",
        "[a():1]",
        "[a()1]",
        "[a()=1] a(2)",
        // Sigma & CPi
        "sigma(x, 3, 1, x*10)",
        "sigma(x, -3, 3)",
        "sigma(y, -3, 3, x*10)",
        "sigma(x, -3, 3, 10)",
        "sigma(x-1, 1, 1, x)",
        "sigma(x, 1.1, 2, x)",
        "sigma(x, 1, 2.1, x)",
        "cpi(x, 3, 1, x*10)",
        "cpi(x, -3, 3)",
        "cpi(y, -3, 3, x*10)",
        "cpi(x, -3, 3, 10)",
        "cpi(x-1, 1, 1, x)",
        "cpi(x, 1.1, 2, x)",
        "cpi(x, 1, 2.1, x)",
        // Solve
        "abs(x)+1 &solve",
        "1 &solve",
        "x*y &solve",
        "1>=2 &solve",
        "1==2==3 &solve"
    };
}