<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>ltb</AssemblyName>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>ltb</ToolCommandName>
        <PackageVersion>0.0.0.0</PackageVersion>
        <Authors>LanLP</Authors>
        <Description>LanLP's math tools collection</Description>
<!--        <PublishAot>true</PublishAot>-->
        <StripSymbols>true</StripSymbols>
        <LangVersion>11</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Cli\Common.Cli.csproj" />
        <ProjectReference Include="..\Delta.Core\Delta.Core.csproj" />
        <ProjectReference Include="..\LCalc\LCalc.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="2.12.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    </ItemGroup>

</Project>
