<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>ltb</AssemblyName>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>ltb</ToolCommandName>
        <PackageVersion>0.0.0.0</PackageVersion>
        <Authors>LanLP</Authors>
        <Description>LanLP's math tools collection</Description>
        <!--                 <PublishAot>true</PublishAot> -->
        <LangVersion>11</LangVersion>
        <StripSymbols>true</StripSymbols>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LCalc.Cli\LCalc.Cli.csproj"/>
        <ProjectReference Include="..\MinMaxFraction.Core\MinMaxFraction.Core.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="Serilog" Version="3.1.1"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
        <PackageReference Include="RadLine" Version="0.6.0"/>
        <PackageReference Include="Spectre.Console.Cli" Version="0.48.0"/>
    </ItemGroup>

</Project>
