<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageVersion>1.8</PackageVersion>
        <RootNamespace>LCalc</RootNamespace>
        <Title>LCalc.Core</Title>
        <Authors>LanLP</Authors>
        <Description>A Fast And Efficient String Calculator</Description>
        <Copyright>LanLP</Copyright>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

</Project>
