<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageVersion>2.0.3</PackageVersion>
        <RootNamespace>LCalc</RootNamespace>
        <Title>LCalc.Core</Title>
        <Authors>LanLP</Authors>
        <Description>A Fast And Efficient String Calculator</Description>
        <Copyright>LanLP</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
    </ItemGroup>

</Project>
