<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
        <OutputType>Exe</OutputType>
        <!-- Allow to interop with javascript -->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <WasmExtraFilesToDeploy Include="AppBundle\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LToolBox.Ui\LToolBox.Ui.csproj"/>
    </ItemGroup>
</Project>
