<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="RadLine" Version="0.6.0"/>
        <PackageReference Include="Spectre.Console.Cli" Version="0.48.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
    </ItemGroup>

</Project>
