<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="LCalc"/>
        <InternalsVisibleTo Include="MinMaxFraction.Core"/>
        <InternalsVisibleTo Include="ltb"/>
        <InternalsVisibleTo Include="LToolBox.Ui"/>
        <InternalsVisibleTo Include="Benchmarks"/>
        <InternalsVisibleTo Include="Common.Cli"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Rationals" Version="2.1.0"/>
    </ItemGroup>

</Project>
