<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net6.0;net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="LCalc.Core" />
        <InternalsVisibleTo Include="Delta.Core" />
        <InternalsVisibleTo Include="ltb" />
        <InternalsVisibleTo Include="LToolBox.Ui" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Rationals" Version="2.1.0" />
    </ItemGroup>

</Project>
