<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="LCalc.Core"/>
        <InternalsVisibleTo Include="Delta.Core"/>
        <InternalsVisibleTo Include="ltb"/>
        <InternalsVisibleTo Include="LToolBox.Ui"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Rationals" Version="2.0.0"/>
    </ItemGroup>

</Project>
